services:
  - type: web
    name: gemini-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: gemini-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: gemini-redis
          property: connectionString

databases:
  - name: gemini-postgres
    databaseName: gemini_backend
    user: postgres

services:
  - type: redis
    name: gemini-redis
    ipAllowList: []

